/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTaskDialog: typeof import('./components/Task/AddTaskDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Auth2FADialog: typeof import('./components/auth/Auth2FADialog.vue')['default']
    BoardTask: typeof import('./components/Task/BoardTask.vue')['default']
    Breadcrumbs: typeof import('./components/Breadcrumbs/index.vue')['default']
    ConfirmDeleteDialog: typeof import('./components/ConfirmDialog/ConfirmDeleteDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./components/SidebarComponent.vue')['default']
    TableTask: typeof import('./components/Task/TableTask.vue')['default']
    TaskCard: typeof import('./components/Task/TaskCard.vue')['default']
    UpdateTaskDialog: typeof import('./components/Task/UpdateTaskDialog.vue')['default']
    ViewTaskDialog: typeof import('./components/Task/ViewTaskDialog.vue')['default']
  }
}
